### ISSUE TITLE
"Fail to find P1xAddr" error

### ISSUE THREAD

**Issue by Cianez** [niko1point0/OnlineCTR#1]
Hi there.

Me and a friend are having a problem trying to connect each other to play the game with OnlineCTR.
This is what your hack reports:
![P1xAdd error2](https://user-images.githubusercontent.com/46445923/69487064-07418e80-0e54-11ea-84fc-82a83a0c1111.png)
We do exactly as the readme file says, it works perfect until it reaches the track loading screen. My friend (the host) can join the game and he only sees 2 players (so that's right), but my loading screen gets stuck forever and stop animating (no ePSXe crash though; I can normally hit "Esc" and close the emulator).
Then my friend that's in-game can play but the second player is just a bot.
The port we're using to host has been forwarded in both our modems. The same thing happens if I host, but for some reason he cannot join me even if UPnP is enabled in my modem settings.
Do you know what it is and how to solve it? Is there a log somewhere that I can provide for your ease?

Thank you in advance.

P.S.: If you care, we would like to help you testing your hack on future versions or debugging/troubleshooting or anything generally.

**Comment by niko1point0** [comment]
Hi, I’m getting this bug too. It used to work fine and then something broke. I’ll be working more on this in the near future.

**Comment by Cianez** [comment]
> 
> 
> Hi, I’m getting this bug too. It used to work fine and then something broke. I’ll be working more on this in the near future.

Let me know if you need help testing it. And thank you for your reply!

**Comment by niko1point0** [comment]
It should be fixed now. Wasn't expecting to have time tonight

Feel free to try it out

**Comment by niko1point0** [comment]
You can play online with me if you'd like. We have a discord server https://discord.gg/56xm9Aj

I'm going to put that in the project description now

**Comment by niko1point0** [comment]
I tested with some friends. This is now fixed.
