### ISSUE TITLE
Unlockable characters

### ISSUE THREAD

**Issue by niko1point0** [niko1point0/OnlineCTR#11]
Some tracks work with Unlockable characters and some dont. This feature is WIP

**Comment by Cianez** [comment]
If you use Bosses (or Penta) the game screws up creating severe graphical glitches for the host only and then it makes ePSXe crash; the client can still play and has no repercussions apart from the fact of not being able to race with the host/opponent.
This has been tested with Penta (host) and Pinstripe (client) in a total of 4 different tracks: Crash Cove, Roo's Tubes, Tiger Temple, Coco Park.
We've tried to play all of them with Coco (host) and Crash (client) and it went perfect.

Some screenshots that shows the issues: 
Host: [https://cdn.discordapp.com/attachments/143512758732718080/650488971532697630/unknown.png](url)
Host: [https://cdn.discordapp.com/attachments/143512758732718080/650489199580938241/unknown.png](url)
Client: [https://cdn.discordapp.com/attachments/641877571000074240/650490136680988691/unknown.png](url)
Client: [https://cdn.discordapp.com/attachments/641877571000074240/650491597460471822/unknown.png](url)

Also, no matter what method we used, this same error keeps happened despite the fact it was working or not:

[https://cdn.discordapp.com/attachments/641877571000074240/650493234245533717/test_2.PNG](url)

We'll now further investigate and report back.

**Comment by niko1point0** [comment]
I do not think it is an LOD problem, because we can drop the LOD with original characters, and no bugs happen. With all these problems, I think we need to put this on hold until character files are dissected and analyzed by the researchers that made CTR-Tools

**Comment by niko1point0** [comment]
This has been fixed. Follow the directions that are listed in OnlineCTR.exe when you run it, in the newest release (coming in like an hour after this post)
